version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:18.04
   environment:
      GIT_EMAIL: 'frelein29@gmail.com'
      GIT_NAME: 'frelein29'
      VENDOR: 'xiaomi'
      DEVICE: 'ugglite'
      VERSION: '2.2'
      product_filename: '*ugglite*.zip'
      chat_id: '-1001378095587'
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc bison build-essential curl flex g++-multilib gcc gcc-multilib clang git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev unzip openjdk-8-jdk python ccache libtinfo5 repo libstdc++6 wget libssl-dev rsync golang-go
           mkdir -p ~/bin
           curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
           chmod a+x ~/bin/repo
           go get -u github.com/tcnksm/ghr
           export PATH=/root/go/bin:$PATH
           git config --global user.email "${GIT_EMAIL}"
           git config --global user.name "{GIT_NAME}"
           git config --global color.ui false
           git clone https://github.com/frelein29/PublishBot PublishBot
           repo init --depth=1 -u git://github.com/SKYHAWK-Recovery-Project/platform_manifest_twrp_omni.git -b 9.0
           repo sync
           git clone https://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME} -b ${CIRCLE_BRANCH} device/${VENDOR}/${DEVICE}
           python3 PublishBot/main.py --before
           export ALLOW_MISSING_DEPENDENCIES=true
           export LC_ALL=C
           source build/envsetup.sh
           lunch omni_${DEVICE}-eng
           make recoveryimage
           export BUILDFILE_ZIP=$(find $(pwd)/out/target/product/${DEVICE}/*ugglite*.zip 2>/dev/null)
           export UPLOAD_PATH=$(pwd)/out/target/product/${DEVICE}/upload/
           mkdir ${UPLOAD_PATH}
           cp $BUILDFILE_ZIP $UPLOAD_PATH
           ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -n "SkyHawk Recovery Project $(echo $DEVICE)" -b "SHRP $(echo $VERSION)"  -c ${CIRCLE_SHA1} -delete ${VERSION} ${UPLOAD_PATH}
           output_file=$(find out/target/product/ugglite/ -name "*ugglite*.zip")
           if [ -f $output_file ]; then
             cp $output_file ./
           else
             python3 PublishBot/main.py --success
             exit 1
           fi
      - run:
           name: Run on fail status
           command: |
              python3 PublishBot/main.py --failed
           when: on_fail
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
